#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# http://weathercook.hatenadiary.jp/entry/20120117/1326778600
cookbook 'windows'
cookbook 'virtualbox'
# cookbook 'firefox'
# cookbook 'autohotkey'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
