source "https://rubygems.org"

gem 'chef'
gem 'librarian-chef'
if RUBY_PLATFORM.downcase =~ /mswin(?!ce)|mingw|cygwin|bccwin/
  gem 'systemu'
  gem 'ffi'
  gem 'ruby-wmi'
  gem 'rdp-ruby-wmi'
  gem 'win32-service'
  gem 'win32-open3' if RUBY_VERSION < '1.9.0'
  gem 'windows-api'
  gem 'windows-pr'
end

