;アウトライン解析 ルールファイル [Tera Term Pro]

INCLUDE /// Control
include /// Control

IF /// Control
ELSE /// Control
ELSEIF /// Control
ENDIF /// Control
if /// Control
else /// Control
elseif /// Control
endif /// Control

FOR /// Control
NEXT /// Control
for /// Control
next /// Control

WHILE /// Control
ENDWHILE /// Control
while /// Control
endwhile /// Control

EXECCMND /// Control
execcmnd /// Control


: /// Label
END /// Label
end /// Label

ende.
